TM-4399 migrate code ownership logic to infra
Squashed commit of the following:

commit f84d167a53f5d84346f8ea3f3e6828567ce4ec9e
Author: aakalaydzhyan <aakalaydzhyan@avito.ru>
Date:   Mon Aug 12 12:36:26 2024 +0300

    TM-4399 migrate code ownership plugin logic to infra

diff --git a/.git_hooks/pre-commit b/.git_hooks/pre-commit
--- a/.git_hooks/pre-commit
+++ b/.git_hooks/pre-commit
@@ -12,9 +12,9 @@ INTERNAL_URLS=$(git diff --cached --no-color --no-prefix --unified=0 \
     | { grep -E --invert-match "links\.k\.avito\.ru" || test $? = 1; } )
 
 if [ -n "${INTERNAL_URLS}" ]; then
-  echo >&2 "WARNING: pre-commit git hook found forbidden internal links in changes:"
+  echo >&2 "ERROR: pre-commit git hook found forbidden internal links in changes:"
   echo >&2 "${INTERNAL_URLS}"
-  # Do not fail because we currently don't publish to GitHub
+  exit 1
 fi
 
 if [ "$COMMIT_CHECK" == "true" ]; then
