MBSA-2217 Add jemalloc to android builder image
Squashed commit of the following:

commit bfe17f19e7a7ef25eda38869a2212b8acf085e62
Author: Vyacheslav Kovalev <vkkovalev@avito.ru>
Date:   Fri Jan 30 17:23:40 2026 +0300

    MBSA-2217 Support jemalloc allocator for CI builds

diff --git a/ci/docker/android-builder/hermetic/Dockerfile b/ci/docker/android-builder/hermetic/Dockerfile
--- a/ci/docker/android-builder/hermetic/Dockerfile
+++ b/ci/docker/android-builder/hermetic/Dockerfile
@@ -7,6 +7,7 @@ ENV DEBIAN_FRONTEND=noninteractive
 RUN \
   apt-get update && \
   apt-get install -y \
+    libjemalloc2 \
     cloc \
     zip \
     unzip \
@@ -23,6 +24,10 @@ RUN \
     shellcheck bats && \
   apt-get clean && \
   apt-get purge
+
+# https://github.com/facebook/jemalloc/wiki/getting-started
+ENV JEMALLOC_PATH=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
+RUN test -f "$JEMALLOC_PATH" || (echo "jemalloc not found at $JEMALLOC_PATH" && exit 1)
 
 ENV LANG C.UTF-8
 ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
